---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 770126738764525568-jX4k8BRmGAe3KYSlkUiVXITSN1kEN6B
:access_token_secret: geR29fjBix6upM8u91bHx8W0x3FjRu1k1PlyRYoDCgSrx
